#!/usr/bin/env perl

use warnings;
use strict;

use feature qw/say/;

use Git::Repository;
use Data::Printer;
use lib::abs 'lib';
use Git::WorkFlow::AstraVer::Notes;

my $r = Git::Repository->new(work_tree => $ENV{CURRENT_PROJECT});

my %notes;
foreach ($r->run('notes')) {
   my @tmp = split ' ';
   $notes{$tmp[1]}{obj} = $tmp[0]
}

foreach (keys %notes) {
   $notes{$_}{content} = $r->run('cat-file' => '-p' => $notes{$_}{obj});
}

foreach (keys %notes) {
   if (Git::WorkFlow::AstraVer::Notes::_validate_ok($notes{$_}{content})) {
      delete $notes{$_}
   }
}

say "Not valid:";
p %notes;

