#!/usr/bin/env perl

use warnings;
use strict;

use feature qw/say/;

use Git::Repository;


sub query_branch
{
   my ($repo, $match) = @_;
   
   sort version_sort
      map {s/^\*?\h++|\h++$//rg}
         $repo->run('branch' => '--list' => $match)
}

sub parse_branch_versions
{
   my @version = map { substr($_, index($_, '-') + 1) } @_;
   my @major = map { substr($_, 0, index($_, '.')) } @version;
   my @minor = map { substr($_, index($_, '.') + 1) } @version;

   map {[$major[$_], $minor[$_]]} (0..$#major)
}

sub version_sort
{
   my @v = parse_branch_versions($a, $b);

   $v[0][0] <=> $v[1][0]
             ||
   $v[0][1] <=> $v[1][1]
}

my $r = Git::Repository->new();

my @devel_branches = query_branch($r, 'devel-*');
my @spec_branches  = query_branch($r, 'spec-*');
my ($ldevel, $lspec) = ($devel_branches[-1], $spec_branches[-1]);

say $ldevel;
say $lspec;

