#!/usr/bin/env perl

use warnings;
use strict;

use feature qw/say/;

use Git::Repository;
use Data::Printer;

my $r = Git::Repository->new();

my %notes;
foreach ($r->run('notes')) {
   my @tmp = split / /;
   $notes{$tmp[1]}{obj} = $tmp[0]
}

foreach (keys %notes) {
   my $subj = $r->run('log' => '-n1' => '--format=%s' => $_);
   my $lbranch = ($r->run('branch' => '--contains' => $_) =~ s/^\*?\h++//r);
   my $rbranch;

   $rbranch = ($r->run('branch' => '-r' => '--contains' => $_) =~ s/^\h++//r)
      unless $lbranch;

   my $content = $r->run('cat-file' => '-p' => $notes{$_}{obj});

   $notes{$_}{log} = $subj;
   if ($lbranch) {
      $notes{$_}{branch} = $lbranch
   } else {
      $notes{$_}{branch} = $rbranch
   }
   $notes{$_}{content} = $content;
}

foreach (keys %notes) {
   unless ($notes{$_}{content} =~ m/[a-f0-9]{7,40}/i) {
      delete $notes{$_}
   }
}

p %notes;

